ALTER TABLE photos
  ADD COLUMN camera VARCHAR(100) DEFAULT NULL AFTER location,
  ADD COLUMN lens VARCHAR(100) DEFAULT NULL AFTER camera,
  ADD COLUMN aperture VARCHAR(20) DEFAULT NULL AFTER lens,
  ADD COLUMN shutter_speed VARCHAR(20) DEFAULT NULL AFTER aperture,
  ADD COLUMN iso INT DEFAULT NULL AFTER shutter_speed;
